# forge modules
mod 'puppetlabs/stdlib'
mod 'theforeman/puppet'
mod 'puppetlabs/apache'
mod 'puppetlabs/concat'
mod 'theforeman/foreman'
mod 'puppetlabs/apt'
mod 'puppetlabs/postgresql'
mod 'puppet/selinux'
mod 'camptocamp-systemd'
mod 'puppetlabs-puppetdb'
mod 'puppetlabs-haproxy', '4.2.0'
mod 'puppet-extlib'
mod 'puppet-php', '7.1.0'
mod 'puppetlabs-kubernetes', '6.0.0'
mod 'puppetlabs-docker', '4.0.0'
mod 'icinga-icinga2', '3.0.0'
mod 'puppetlabs-mysql', '11.0.0'
#not from forge
#profile code and local modules
