# forge modules
mod 'puppetlabs/stdlib'
mod 'theforeman/puppet'
mod 'puppetlabs/apache'
mod 'puppetlabs/concat'
mod 'theforeman/foreman'
mod 'puppetlabs/apt'
mod 'puppetlabs/postgresql'
mod 'puppet/selinux'
mod 'camptocamp-systemd'
mod 'puppetlabs-puppetdb'
mod 'puppetlabs-haproxy'
mod 'puppet-extlib'
mod 'puppet-php'
mod 'puppetlabs-kubernetes'
mod 'puppetlabs-docker'
mod 'icinga-icinga2'
mod 'puppetlabs-mysql'
#not from forge
#profile code and local modules
